# Generated by rust2rpm 10
%bcond_without check

%global crate rpick

Name:           rust-%{crate}
Version:        0.4.0
Release:        5%{?dist}
Summary:        Helps you pick items from a list by various algorithms

# Upstream license specification: GPL-3.0
# The binary license is the combination of rpick's license and all of its dependencies. You can use
# cargo-license to find these: https://github.com/onur/cargo-license
License:        GPLv3 and Apache-2.0 and BSD-2 and CC0-1.0 and ISC and MIT
URL:            https://crates.io/crates/rpick
Source:         %{crates_source}
# Initial patched metadata
# * Update dirs to 2, https://gitlab.com/bowlofeggs/rpick/merge_requests/22
Patch0:         rpick-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Helps you pick items from a list by various algorithms. Example uses: pick a
restaurant you haven't been to in a while, or an album to listen to.}

%description %{_description}

%if ! %{__cargo_skip_build}
%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md
%{_bindir}/rpick
%endif

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.0-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Nov 18 2019 Randy Barlow <bowlofeggs@fedoraproject.org> - 0.4.0-4
- Correct the license to reflect the licenses of all dependencies, as they are bundled.

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Wed Jun 19 13:20:06 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.0-2
- Update dirs to 2

* Sun May 12 2019 Randy Barlow <bowlofeggs@fedoraproject.org> - 0.4.0-1
- Update to 0.4.0.
- https://gitlab.com/bowlofeggs/rpick/blob/0.4.0/CHANGELOG.md

* Sat May 04 2019 Randy Barlow <bowlofeggs@fedoraproject.org> - 0.3.1-1
- Update to 0.3.1 (#1698689).
- https://gitlab.com/bowlofeggs/rpick/blob/0.3.1/CHANGELOG.md

* Thu Apr 11 16:11:59 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.0-1
- Update to 0.3.0

* Wed Mar 13 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-1
- Update to 0.2.0

* Tue Mar 05 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.0-1
- Update to 0.1.0

* Fri Feb 22 2019 Randy Barlow <randy@electronsweatshop.com> - 0.0.0-1
- Initial package
